// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvzupescdvkivhnrozkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2enVwZXNjZHZraXZobnJvemt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDIyNjYsImV4cCI6MjA2OTc3ODI2Nn0.c9VcldlZy7f6BBTXVMUUSQ0wiP96wRTx6fLGZtCVcJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});